server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: bank_rest
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1111}
    driver-class-name: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.xml
